### ISSUE TITLE
sad to see its not maintained any more.

### ISSUE THREAD

**Issue by inoshy** [sgolle/coolprop-rs#1]
: (

**Comment by sgolle** [comment]
Is there anything not working right now with the current CoolProp version? The jump to a full featured object-oriented wrapper like in python is quiet high and I don't have the time right now to carry out this amount of work.

**Comment by inoshy** [comment]
I have a college project that told us explicitly to use coolprop and i only knew rust so i was searching for a crate. when i found one, i was like, "oh, the last commit is an year ago, things are surely going to break" XD
I am going to use it soon. thanks a lot though! :))

**Comment by sgolle** [comment]
I close this because the wrapper should still work with the current CoolProp version
