### ISSUE TITLE
How do I installl shared library?

### ISSUE THREAD

**Issue by inoshy** [sgolle/coolprop-rs#2]
Hi, having found no documentation about how to build the coolprop project,  i cloned the repository and tried to build it myself (but i failed) now I cant install the shared libraries to make this crate work.
Would you shed some light how can I install them? thanks! :)

**Comment by sgolle** [comment]
The documentation with build instructions ist available here: [http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#shared-library](url)

Linux should work fine. I didn't try Windows though.

**Comment by inoshy** [comment]
Thank you so much sgolle!! I am so grateful for this crate 😁 😁

**Comment by sgolle** [comment]
You're welcome
