### ISSUE TITLE
CoolPropLib.h not found in Mac 

### ISSUE THREAD

**Issue by gganapat** [sgolle/coolprop-rs#3]
Hi:

I was trying to use your CoolProp wrapper on my Mac. I have libCoolProp.dylib in /usr/local/lib and CoolPropLib.h in /usr/local/include and made sure the paths are sourced correctly and included coolprop-rs="0.2.0" in Cargo.toml. When I tried running your subset example, I get errors as below:

$: cargo run

   Compiling coolprop-rs v0.2.0
error: failed to run custom build command for 'coolprop-rs v0.2.0/'

Caused by:
  process didn't exit successfully: `/Users/gani/Library/CloudStorage/OneDrive-Personal/rust_projects/rust_coolprop/target/debug/build/coolprop-rs-0bc24761821d7ba6/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=CoolProp
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:2:10: fatal error: 'CoolPropLib.h' file not found
  wrapper.h:2:10: fatal error: 'CoolPropLib.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /Users/gani/.cargo/registry/src/github.com-1ecc6299db9ec823/coolprop-rs-0.2.0/build.rs:27:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by sgolle** [comment]
Sorry for the late reply. I don't use a Mac, but I suspect, this is not an issue with the wrapper but with the main CoolProp installation. This wrapper does not install CoolPropLib.h but the CoolProp build does. So please refer to the main repository.
